[package]
name = "ko-rpc-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpsee = { version = "0.15", features = ["http-server", "macros"] }

ko-protocol = { path = "../../protocol" }
