[package]
name = "ko-driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ko-protocol = { path = "./protocol" }
ko-core = { path = "./core" }
ko-core-assembler = { path = "./core/assembler" }
ko-core-driver = { path = "./core/driver" }
ko-core-executor = { path = "./core/executor" }
