# type_args is script_args which generates project type_id
project_type_args = "0xdd53c2bb4be8102693feb11b8325cbd69b1265cb5f215c6cfff5fefbaede50ba"

# the deployer of this project
project_owner_privkey = "0x8d929e962f940f75aa32054f19a5ea2ce70ae30bfe4ff7cf2dbed70d556265df"

# knside-out contract code_hash
project_code_hash = "0x8f11b7a80bb50a518cd29170cbc72b2ab8ef94fc8297f75cfa9f8917d5057e4b"

# url for connecting CKB node
ckb_url = "http://127.0.0.1:8114"

# url for connecting ckb indexer service
ckb_indexer_url = "http://127.0.0.1:8116"

# endpoint for running rpc server
rpc_endpoint = "0.0.0.0:8090"

# necessary cell deps
project_cell_deps = [
    # omni
    # { transaction_hash = "", cell_index = 0, dep_type = 0 },
    # secp256k1
    { transaction_hash = "0xc6bffa9ca9a9dadfec83c0307eee18fe88e42a00d05068510d799e3e4ad3ee87", cell_index = 0, dep_type = 1 },
    # knside-out
    { transaction_hash = "0xb769ef9ccc18b5a883a4a44f31217036458be38dbef874a10e69d8f5b0f322a0", cell_index = 0, dep_type = 0 },
]
