# type_args is script_args which generates project type_id
project_type_args = ""

# the unique hash for presenting project cell
project_type_id = ""

# the deployer of this project
project_owner_privkey = ""

# knside-out contract code_hash
project_code_hash = ""

# url for connecting CKB node
ckb_url = ""

# url for connecting ckb indexer service
ckb_indexer_url = ""

# necessary cell deps
project_cell_deps = [
    # omni
    { transaction_hash = "", cell_index = 0 },
    # secp256k1
    { transaction_hash = "", cell_index = 0 },
]
