# type_args is script_args which generates project type_id
project_type_args = "0xd6568eda1c20e30b41cd15be2f9ab8db9446561097ee801cafabdb6ca6133e05"

# the deployer of this project
project_owner_privkey = "0x9a8fc5c463841c152800ec45ef4ceb03586177a7e6a9f34a6e40256310325e43"

# knside-out contract code_hash
project_code_hash = "0x0883e9527e2798d7bb3540b1186297464fdfb71bf59566971b0824c781aaa6c0"

# url for connecting CKB node
ckb_url = "http://127.0.0.1:8114"

# url for connecting ckb indexer service
ckb_indexer_url = "http://127.0.0.1:8116"

# necessary cell deps
project_cell_deps = [
    # omni
    # { transaction_hash = "", cell_index = 0, dep_type = 0 },
    # secp256k1
    { transaction_hash = "0x5c7b70f4fd242ff0fb703de908e2e7eef21621b640fe9a9c752643021a87bc1f", cell_index = 0, dep_type = 1 },
    # knside-out
    { transaction_hash = "0xb88a68436c16dbdfbd5d3c3e38c5dcd4905514e0c8ead8e0b1b8533bc63d32e0", cell_index = 0, dep_type = 0 },
]
