# the default manager ckb address
project_manager_address = "ckt1qyq93wzur9h9l6qwyk6d4dvkuufp6gvl08aszz5syl"

# the default manager for project global cell management
project_manager_privkey = "0x8d929e962f940f75aa32054f19a5ea2ce70ae30bfe4ff7cf2dbed70d556265df"

# knside-out contract code_hash
project_code_hash = "0xe7b5a4f6bbaf17c4f4afcc24805021c67bdd8db583097bcb38b21083ac2d1558"

# url for connecting CKB node
ckb_url = "http://127.0.0.1:8114/"

# url for connecting ckb indexer service
ckb_indexer_url = "http://127.0.0.1:8116/"

# endpoint for running rpc server
rpc_endpoint = "0.0.0.0:8090"

# interval time for persistence of contexts status
persist_interval_sec = 60

# necessary cell deps
project_cell_deps = [
    # omni
    # { transaction_hash = "", cell_index = 0, dep_type = 0 },
    # secp256k1
    { transaction_hash = "0xc6bffa9ca9a9dadfec83c0307eee18fe88e42a00d05068510d799e3e4ad3ee87", cell_index = 0, dep_type = 1 },
    # knside-out
    { transaction_hash = "0x785e1680ae0f677b177954c41c297f50b711e0ddf0fc44c9cb92959cee6901cf", cell_index = 0, dep_type = 0 },
]

[drive_settings]
# the time duration of drive loop interval
drive_interval_sec = 3

# the max number of transaction inputs in one drive loop
max_reqeusts_count = 20

# the block confirmations count to checkout knside-out transaction status
block_confirms_count = 3

# the max idle duration of each knside-out context
kickout_idle_sec = 360