# the default manager ckb address
project_manager_address = "ckt1qyq93wzur9h9l6qwyk6d4dvkuufp6gvl08aszz5syl"

# the default manager for project global cell management
project_manager_privkey = "0x8d929e962f940f75aa32054f19a5ea2ce70ae30bfe4ff7cf2dbed70d556265df"

# knside-out contract code_hash
project_code_hash = "0x05d0e558c42c8f52d0addc2dee8dda669b66637650c4e8a0c3845c5c1f395ece"

# url for connecting CKB node e.g. https://testnet.ckbapp.dev/
ckb_url = "http://127.0.0.1:8114"

# url for connecting ckb indexer service
ckb_indexer_url = "http://127.0.0.1:8116"

# endpoint for running rpc server
rpc_endpoint = "0.0.0.0:8090"

# interval time for persistence of contexts status
persist_interval_sec = 60

# necessary cell deps
project_cell_deps = [
    # omni
    # { transaction_hash = "", cell_index = 0, dep_type = 0 },
    # secp256k1
    { transaction_hash = "0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37", cell_index = 0, dep_type = 1 },
    # knside-out
    { transaction_hash = "0x416e5e0d4925ab21831920741866d994b0c5a2a22689d0d8c994d23e4556b554", cell_index = 0, dep_type = 0 },
]

[drive_settings]
# the time duration of drive loop interval
drive_interval_sec = 3

# the max number of transaction inputs in one drive loop
max_reqeusts_count = 20

# the block confirmations count to checkout knside-out transaction status
block_confirms_count = 0

# the max idle duration of each knside-out context
kickout_idle_sec = 720